### ISSUE TITLE
导入时程序无提示退出

### ISSUE THREAD

**Issue by XKBY** [kressety/MinecraftModsTranslator#4]
百度API测试无误
程序和模组已经放入单独文件夹
启动程序没有问题，启动后导入jar选择文件后程序瞬间消失退出

测试了三个模组
Aquafina_no_pollution_1.0.0
Decoration Mod 1.6 (Ver 1.16.5)
Farmers_Extra_Foods_1.2
程序均会退出

**Comment by XKBY** [comment]
修正：已知使用网络代理服务会导致程序退出
若不使用代理的情况下测试的另外十多个模组，全部是“未找到可翻译文件”错误。

**Comment by kressety** [comment]
感谢您的反馈，前段时间有事，很抱歉现在才给您回复。
关于网络问题，挂代理确实会导致连接不上百度API，尽量在国内的网络环境下使用软件吧。
关于“未找到可翻译文件”问题，在新发布的版本中我已经修复了这个bug，并测试了包括Farmers_Extra_Foods在内的数个模组，均可以正常运行。
链接附下，如有其他问题欢迎反馈。
[Minecraft mods 辅助翻译器v0.0.2](https://github.com/kressety/MinecraftModsTranslator/releases/tag/v0.0.2)

**Comment by XKBY** [comment]
感谢，已经解决了，汉化模组现在方便很多了，期待后续更新和更多api支持，加油
